# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Launch tests with Maven
      run:  mvn test
    - name: Check Out Repo 
      uses: actions/checkout@v2
          # Build and push docker
     #- name: Build and Push Docker
     # uses: docker/build-push-action@v1
     # with:
     #     username: ${{ secrets.DOCKER_USERNAME }}
     #     password: ${{ secrets.DOCKER_PASSWORD }}
     #     repository: mpazlaboratorio/prueba
     #     tags: lastest  
     #     tag_with_ref: true
     #     tag_with_sha: true
        #tags: ${{ github.sha }}  
